//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1124WCFPictureClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPicture")]
    public interface IPicture {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPicture/GetPicture", ReplyAction="http://tempuri.org/IPicture/GetPictureResponse")]
        byte[] GetPicture(string strFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPicture/GetPictureList", ReplyAction="http://tempuri.org/IPicture/GetPictureListResponse")]
        string[] GetPictureList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPicture/UploadPicutre", ReplyAction="http://tempuri.org/IPicture/UploadPicutreResponse")]
        bool UploadPicutre(string strFileName, byte[] bytePic);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPictureChannel : _1124WCFPictureClient.ServiceReference1.IPicture, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PictureClient : System.ServiceModel.ClientBase<_1124WCFPictureClient.ServiceReference1.IPicture>, _1124WCFPictureClient.ServiceReference1.IPicture {
        
        public PictureClient() {
        }
        
        public PictureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PictureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PictureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PictureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetPicture(string strFileName) {
            return base.Channel.GetPicture(strFileName);
        }
        
        public string[] GetPictureList() {
            return base.Channel.GetPictureList();
        }
        
        public bool UploadPicutre(string strFileName, byte[] bytePic) {
            return base.Channel.UploadPicutre(strFileName, bytePic);
        }
    }
}
