//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1201_Form.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stu", Namespace="http://schemas.datacontract.org/2004/07/_1203_Service")]
    [System.SerializableAttribute()]
    public partial class Stu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _1201_Form.ServiceReference1.Enumclass STypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _1201_Form.ServiceReference1.Enumclass SType {
            get {
                return this.STypeField;
            }
            set {
                if ((this.STypeField.Equals(value) != true)) {
                    this.STypeField = value;
                    this.RaisePropertyChanged("SType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enumclass", Namespace="http://schemas.datacontract.org/2004/07/_1203_Service")]
    public enum Enumclass : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IT = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GAME = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETC = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStuManager")]
    public interface IStuManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/PrintAll", ReplyAction="http://tempuri.org/IStuManager/PrintAllResponse")]
        _1201_Form.ServiceReference1.Stu[] PrintAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/PrintAll", ReplyAction="http://tempuri.org/IStuManager/PrintAllResponse")]
        System.Threading.Tasks.Task<_1201_Form.ServiceReference1.Stu[]> PrintAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/StuInsert", ReplyAction="http://tempuri.org/IStuManager/StuInsertResponse")]
        bool StuInsert(_1201_Form.ServiceReference1.Stu stu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/StuInsert", ReplyAction="http://tempuri.org/IStuManager/StuInsertResponse")]
        System.Threading.Tasks.Task<bool> StuInsertAsync(_1201_Form.ServiceReference1.Stu stu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/NumberToStudent", ReplyAction="http://tempuri.org/IStuManager/NumberToStudentResponse")]
        _1201_Form.ServiceReference1.Stu NumberToStudent(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/NumberToStudent", ReplyAction="http://tempuri.org/IStuManager/NumberToStudentResponse")]
        System.Threading.Tasks.Task<_1201_Form.ServiceReference1.Stu> NumberToStudentAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/StuDelete", ReplyAction="http://tempuri.org/IStuManager/StuDeleteResponse")]
        bool StuDelete(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/StuDelete", ReplyAction="http://tempuri.org/IStuManager/StuDeleteResponse")]
        System.Threading.Tasks.Task<bool> StuDeleteAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/StuUpdate", ReplyAction="http://tempuri.org/IStuManager/StuUpdateResponse")]
        bool StuUpdate(int number, _1201_Form.ServiceReference1.Enumclass type, int grade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuManager/StuUpdate", ReplyAction="http://tempuri.org/IStuManager/StuUpdateResponse")]
        System.Threading.Tasks.Task<bool> StuUpdateAsync(int number, _1201_Form.ServiceReference1.Enumclass type, int grade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStuManagerChannel : _1201_Form.ServiceReference1.IStuManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StuManagerClient : System.ServiceModel.ClientBase<_1201_Form.ServiceReference1.IStuManager>, _1201_Form.ServiceReference1.IStuManager {
        
        public StuManagerClient() {
        }
        
        public StuManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StuManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StuManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StuManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _1201_Form.ServiceReference1.Stu[] PrintAll() {
            return base.Channel.PrintAll();
        }
        
        public System.Threading.Tasks.Task<_1201_Form.ServiceReference1.Stu[]> PrintAllAsync() {
            return base.Channel.PrintAllAsync();
        }
        
        public bool StuInsert(_1201_Form.ServiceReference1.Stu stu) {
            return base.Channel.StuInsert(stu);
        }
        
        public System.Threading.Tasks.Task<bool> StuInsertAsync(_1201_Form.ServiceReference1.Stu stu) {
            return base.Channel.StuInsertAsync(stu);
        }
        
        public _1201_Form.ServiceReference1.Stu NumberToStudent(int number) {
            return base.Channel.NumberToStudent(number);
        }
        
        public System.Threading.Tasks.Task<_1201_Form.ServiceReference1.Stu> NumberToStudentAsync(int number) {
            return base.Channel.NumberToStudentAsync(number);
        }
        
        public bool StuDelete(int number) {
            return base.Channel.StuDelete(number);
        }
        
        public System.Threading.Tasks.Task<bool> StuDeleteAsync(int number) {
            return base.Channel.StuDeleteAsync(number);
        }
        
        public bool StuUpdate(int number, _1201_Form.ServiceReference1.Enumclass type, int grade) {
            return base.Channel.StuUpdate(number, type, grade);
        }
        
        public System.Threading.Tasks.Task<bool> StuUpdateAsync(int number, _1201_Form.ServiceReference1.Enumclass type, int grade) {
            return base.Channel.StuUpdateAsync(number, type, grade);
        }
    }
}
