//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1124TransClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Trans")]
    public interface Trans {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Trans/TransText", ReplyAction="http://tempuri.org/Trans/TransTextResponse")]
        string TransText(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Trans/TransText", ReplyAction="http://tempuri.org/Trans/TransTextResponse")]
        System.Threading.Tasks.Task<string> TransTextAsync(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransChannel : _1124TransClient.ServiceReference1.Trans, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransClient : System.ServiceModel.ClientBase<_1124TransClient.ServiceReference1.Trans>, _1124TransClient.ServiceReference1.Trans {
        
        public TransClient() {
        }
        
        public TransClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TransText(string msg) {
            return base.Channel.TransText(msg);
        }
        
        public System.Threading.Tasks.Task<string> TransTextAsync(string msg) {
            return base.Channel.TransTextAsync(msg);
        }
    }
}
